#!/usr/bin/env python3

# Copyright John Allsup 2015
# Released under the GNU General Public License v3
# See file LICENSE

import sys,os
import re

args = sys.argv[1:]

if len(args) < 3:
    print("filesr searchpat replpat <files>")
    sys.exit(1)

s,r = tuple(args[:2])
files = args[2:]
print(42,s,r)

import uuid,os.path
while True:
    t = str(uuid.uuid4())
    if not os.path.exists(t):
        break
print("Temp name {}".format(t))

rs = re.compile(s)
for x in files:
    y = rs.sub(r,x)
    if x == y:
        pass
    elif os.path.exists(y):
        print("{} already exists".format(y))
    else:
        xa = x.lower()
        ya = y.lower()
        if xa == ya:
            print("Capitalisation issue")
            print("Using temp name {}".format(t))
            print(x,y)
            os.rename(x,t)
            os.rename(t,y)
        else:
            print("Just rename")
            print(x,y)
            os.rename(x,y)

